/**
 * Anti-bot validation utilities for signup flow.
 * Detects gibberish restaurant names generated by bots.
 */

const VOWELS = new Set('aeiouyàâäéèêëïîôùûüœæ');

/**
 * Check if a restaurant name looks like a random/gibberish string.
 * Returns an error key if invalid, or null if valid.
 */
export function validateRestaurantName(name: string): string | null {
  const trimmed = name.trim();

  // Too short
  if (trimmed.length < 2) return 'error_name_too_short';

  // Too long without spaces (real names have spaces: "Le Petit Bistro")
  if (trimmed.length > 30 && !trimmed.includes(' ')) return 'error_name_gibberish';

  // Check vowel/consonant ratio on the alphabetic portion
  const alpha = trimmed.toLowerCase().replace(/[^a-zàâäéèêëïîôùûüœæ]/g, '');
  if (alpha.length >= 4) {
    const vowelCount = [...alpha].filter(c => VOWELS.has(c)).length;
    const ratio = vowelCount / alpha.length;
    // Natural language typically has 30-50% vowels
    // Gibberish like "wutdlOzhpBLpqZNoYsXFGVI" has very few
    if (ratio < 0.15) return 'error_name_gibberish';
  }

  // Check for long consecutive consonant runs (>5 in a row is unnatural)
  const consonantRun = alpha.replace(/[aeiouyàâäéèêëïîôùûüœæ]/g, ' ').split(' ');
  if (consonantRun.some(run => run.length > 5)) return 'error_name_gibberish';

  // Excessive length overall
  if (trimmed.length > 80) return 'error_name_too_long';

  return null;
}

/**
 * Honeypot check — returns true if the honeypot field was filled (= bot).
 */
export function isHoneypotFilled(value: string): boolean {
  return value.length > 0;
}
