#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const el = JSON.parse(fs.readFileSync(path.join(__dirname, '../messages/el.json'), 'utf8'));

// Patch all remaining untranslated keys
const patch = {
  SocialHub: {
    connect_meta_title: 'Meta (Facebook & Instagram)',
    connect_tiktok_title: 'TikTok',
  },
  LandingPage: {
    features_card2_live: 'Ζωντανή Ροή',
    language_english: 'English',
    language_spanish: 'Español',
    philosophy_bg_alt: 'Οργανική υφή εσωτερικού χώρου εστιατορίου fine dining',
    philosophy_intro: 'Η διεύθυνση ενός εστιατορίου σήμερα μοιάζει με το να κυβερνάς ένα πλοίο μέσα σε ομίχλη — χωρίς όργανα, μαντεύετε. Με δεδομένα, πλοηγείτε.',
    philosophy_vision: 'Το RiveHub είναι η πυξίδα που μετατρέπει την αβεβαιότητα σε διορθώσεις πορείας.',
    philosophy_pillar1_title: 'Ενισχύστε την εμπειρογνωμοσύνη σας — σε κάθε κατάστρωμα',
    philosophy_pillar1_desc: 'Το RiveHub δεν αντικαθιστά την εμπειρογνωμοσύνη σας — την ενισχύει με δεδομένα και τη μεταδίδει σε κάθε μέλος του πληρώματος, στη γλώσσα τους.',
    philosophy_pillar2_title: 'Αθόρυβες διαρροές κέρδους σε τρικυμισμένα νερά',
    philosophy_pillar2_desc: 'Κάθε ελλείπον σημείο δεδομένων είναι μια διαρροή κάτω από τη γραμμή νερού. Το σόναρ του RiveHub το κάνει ορατό πριν βουλιάξετε.',
    philosophy_pillar3_title: 'Η ευφυΐα σας, το σκάφος σας',
    philosophy_pillar3_desc: 'Όσο περισσότερο βαθμονομείτε, τόσο περισσότερο το σκάφος σας μαθαίνει τα νερά. Είναι η δική σας ευφυΐα — όχι η δική μας.',
    hero_loss_hook: 'Κάθε μέρα χωρίς δεδομένα είναι αόρατη σπατάλη.',
    hero_borderless_hook: 'Διαθέσιμο σε {count} γλώσσες',
    f3_count_label: 'γλώσσες & διάλεκτοι υποστηρίζονται',
    calculator_title: 'Πόσο σας κοστίζει η αβεβαιότητα;',
    calculator_subtitle: 'Εκτιμήστε το κόστος υπερπαραγωγής χωρίς αξιόπιστα δεδομένα.',
    social_proof_banner: 'Σχεδιασμένο για εστιατόρια fine dining στο Κεμπέκ',
    protocol_title: 'Βαθμολογία Ευφυΐας',
    protocol_desc: 'Το IQ της κουζίνας σας αυξάνεται με κάθε σύνδεση.',
    protocol_phase1_title: '40% — Συνδέστε τις κρατήσεις σας',
    protocol_phase1_desc: 'Ένα κουμπί, και το RiveHub αρχίζει να μαθαίνει τον ρυθμό σας.',
    protocol_phase2_title: '65% — Συνδέστε το POS σας',
    protocol_phase2_desc: 'Οι παλαιότερες πωλήσεις σας γίνονται προβλέψεις ανά προϊόν.',
    protocol_phase3_title: '95% — Βαθμονομήστε το σύστημά σας',
    protocol_phase3_desc: '30 δευτερόλεπτα ανατροφοδότησης την ημέρα και το σύστημά σας φτάνει 92% ακρίβεια.',
    protocol_cta: 'Ξεκινήστε στο 40%',
    footer_desc: 'Αλγοριθμική ευφυΐα για γαστρονομικά εστιατόρια.',
    footer_status: 'Σύστημα Λειτουργικό',
    footer_rights: '© 2026 RiveHub. Με επιφύλαξη παντός δικαιώματος.',
    widget_yield: 'Απόδοση',
    widget_core: 'Πυρήνας',
    widget_running: 'Σε λειτουργία',
    features_card1_fridge: 'Ψυγείο #2 — Ψυκτικός θάλαμος',
    features_card1_ai_badge: 'Πρόταση AI',
    features_card1_ai_suggestion: 'Θερμοκρασία > 4°C ανιχνεύθηκε. Ελέγξτε σφράγιση πόρτας. Απομονώστε τρόφιμα υψηλού κινδύνου εάν > 2 ώρες.',
    features_card2_line1: 'Κόστος τροφίμων: 28%',
    features_card2_line2: 'Στόχος: < 30%',
    features_card2_alert: 'Σολομός +$0.50/kg αυτή την εβδομάδα',
    features_card2_action: 'Αυτόματη ενημέρωση μενού',
    features_card3_source_lang: 'Γαλλικά',
    features_card3_source_text: 'Καθαρίστε το πάτωμα απόψε',
    features_card3_target_lang: 'Μπενγκάλι',
    features_card3_target_text: 'আজ রাতে মেঝে পরিষ্কার করুন',
    footer_privacy: 'Πολιτική Απορρήτου',
    footer_terms: 'Όροι Χρήσης',
    sticky_cta: 'Ξεκινήστε Δωρεάν',
    nano_banana_title: 'Η Ταξιαρχία',
    nano_banana_subtitle: 'Πολύγλωσση ομάδα σας',
    nano_banana_badge: 'AI',
    nest_net_profit: 'Καθαρό Κέρδος',
    nest_cash_flow: 'Ταμειακή Ροή',
    nb_haccp_title: 'HACCP Runner',
    nb_haccp_desc: 'Αυτοματοποιημένοι έλεγχοι συμμόρφωσης',
    nb_sonar_title: 'Sonar',
    nb_sonar_desc: 'Ελέγχοι & μήτρα δεξιοτήτων',
    nb_ocr_title: 'Ο Φακός',
    nb_ocr_desc: 'Σάρωση τιμολογίων OCR',
    nb_voice_title: 'Φωνητική Υπαγόρευση',
    nb_voice_desc: 'Σημειώσεις AI με φωνή',
    features_title: 'Χαρακτηριστικά',
    f1_title: 'Ευφυές Ημερολόγιο',
    f1_desc: 'Σημειώσεις AI, αυτόματη ταξινόμηση, επείγοντα — κάθε μέλος γράφει στη γλώσσα του.',
    f1_ex1: 'Αυτόματη ταξινόμηση κατά κατηγορία',
    f1_ex2: 'Μετάφραση σε πραγματικό χρόνο σε {count} γλώσσες',
    f1_ex3: 'Εξαγωγή αναφοράς ενός κλικ',
    f2_title: 'Κόστος Τροφίμων & Περιθώρια',
    f2_desc: 'Αυτόματος υπολογισμός περιθωρίου ανά πιάτο. Ανίχνευση αθόρυβου πληθωρισμού σε πραγματικό χρόνο.',
    f2_ex1: 'Ζωντανός υπολογισμός κόστους ανά μερίδα',
    f2_ex2: 'Ειδοποιήσεις πληθωρισμού προμηθευτή',
    f2_ex3: 'Ολοκληρωμένο κόστος εργασίας',
    f3_title: 'Πολύγλωσσο Πλήρωμα',
    f3_desc: 'Κάθε μέλος του πληρώματος διαβάζει και γράφει στη μητρική του γλώσσα. Αυτόματα.',
    f3_ex1: 'Αυτόματη ανίχνευση γλώσσας',
    f3_ex2: 'Κάρτες συνταγών σε κάθε γλώσσα',
    f3_ex3: 'Διαδικασίες ασφαλείας μεταφρασμένες',
    f3_source_example: 'Καθαρίστε το πάτωμα απόψε',
    f3_target_example: 'আজ রাতে মেঝে পরিষ্কার করুন',
    integrations_banner: 'Ενσωματώνεται με Toast, Square, Lightspeed, SumUp, Zettle & περισσότερα',
    f4_title: 'Σαρωτής Τιμολογίων OCR',
    f4_desc: 'Βγάλτε φωτογραφία. Η AI εξάγει τιμές, ενημερώνει κόστη, εντοπίζει αυξήσεις.',
    f4_ex1: 'Εξαγωγή Claude Vision',
    f4_ex2: 'Αυτόματη ενημέρωση τιμών υλικών',
    f4_ex3: 'Ανίχνευση μετακίνησης τιμών',
    f5_title: 'Μηχανική Μενού',
    f5_desc: 'Ταξινόμηση BCG — Φάρος, Άγκυρα, Παρέκκλιση, Ύφαλος. Βελτιστοποιήστε το μενού σας με AI.',
    f5_ex1: 'Μήτρα BCG σε πραγματικό χρόνο',
    f5_ex2: 'Συστάσεις AI ανά πιάτο',
    f5_ex3: 'Συγχρονισμός δεδομένων πωλήσεων POS',
    f6_title: 'Δημιουργός Instagram',
    f6_desc: 'Δημοσιεύσεις AI για τα πιάτα σας με λεζάντες, hashtags και βέλτιστη ώρα δημοσίευσης.',
    f6_ex1: 'Λεζάντες AI ανά πιάτο',
    f6_ex2: 'Αυτόματα hashtags',
    f6_ex3: 'Πρόταση βέλτιστης ώρας',
    philosophy_approach: 'Η Προσέγγισή μας',
    f7_title: 'Έξυπνη Προετοιμασία',
    f7_desc: 'Λίστες προετοιμασίας βασισμένες σε AI από κρατήσεις, πωλήσεις και καιρό.',
    f7_ex1: 'Πρόβλεψη ανά πιάτο',
    f7_ex2: 'Ενσωμάτωση κρατήσεων',
    f7_ex3: 'Βρόχος ανατροφοδότησης μετά την υπηρεσία',
    f8_title: 'Κρατήσεις',
    f8_desc: 'Ζωντανή ροή κρατήσεων από Libro, Resy, Zenchef σε ένα μέρος.',
    f8_ex1: 'Συγχρονισμός πολλαπλών πλατφορμών',
    f8_ex2: 'Πρόβλεψη περαστικών',
    f8_ex3: 'Ιστορικό κρατήσεων',
    f1_mock_date: 'Σήμερα, 14:32',
    f1_mock_urgent: 'ΕΠΕΙΓΟΝ',
    f1_mock_entry1: 'Ψυγείο #2 πάνω από 4°C — ελέγξτε πόρτα',
    f1_mock_ai_task: 'AI: Απομονώστε γαλακτοκομικά εντός 2 ωρών',
    f1_mock_entry2: 'Νέος σολομός παρελήφθη — ενημέρωση τιμής',
    f1_mock_ai_badge: 'AI',
    f2_mock_alert: 'Σολομός +$0.50/kg',
    f2_mock_action: 'Αυτόματη ενημέρωση κόστους',
    bcg_stars: 'Αστέρια',
    bcg_cashcows: 'Άγκυρες',
    bcg_deadweights: 'Ύφαλοι',
    bcg_puzzles: 'Παρεκκλίσεις',
    pos_sync_text: 'Συγχρονισμός POS',
    ocr_product: 'ΦΙΛΕΤΟ ΣΟΛΟΜΟΥ',
    ocr_price: '$24.50/KG',
    ocr_alert: '+12% vs προηγ. μήνα',
    ocr_status: 'Κόστος Ενημερώθηκε',
    prep_header: 'Λίστα Προετοιμασίας — Σήμερα',
    prep_item_beef: 'Μπριζόλα',
    prep_item_salmon: 'Σολομός',
    prep_item_potato: 'Πατάτες',
    prep_item_cream: 'Κρέμα',
    prep_cost_label: 'Εκτ. κόστος',
    res_confirmed: 'Επιβεβαιωμένο',
    res_cancelled: 'Ακυρωμένο',
    f6_mock_caption: 'Το αριστούργημα του σεφ μας — φρέσκος σολομός σε κρούστα βοτάνων 🐟✨',
    tier_essential_name: 'Essence',
    tier_essential_badge: 'Δωρεάν',
    tier_essential_desc: 'Ξεκινήστε με βασικά εργαλεία.',
    tier_performance_name: 'Horizon',
    tier_performance_badge: 'Δημοφιλές',
    tier_performance_desc: 'Αυτοματοποιήστε τις λειτουργίες σας.',
    tier_intelligence_name: 'Intelligence',
    tier_intelligence_badge: 'Pro',
    tier_intelligence_desc: 'Πλήρης ευφυΐα δεδομένων.',
    f9_title: 'Παρακολούθηση Εγγυήσεων',
    f9_desc: 'Παρακολουθήστε βαρέλια και εγγυήσεις μπουκαλιών ξεχωριστά από το Κόστος Τροφίμων.',
    f9_ex1: 'Αυτόματη εξαγωγή OCR',
    f9_ex2: 'Ελεγχος κατάστασης κατοχής/επιστροφής',
    f9_ex3: 'Ανάκτηση πίστωσης',
    beta_badge: 'BETA',
    examples_title: 'Παραδείγματα',
    res_mock_last_sync: 'Τελ. συγχρ.: πριν 2 λ.',
    res_mock_live: 'Ζωντανό',
    prep_mock_auto: 'Αυτόματο',
    prep_mock_recipe: 'Συνταγή',
    prep_mock_resa: 'Κράτηση',
    prep_mock_pos: 'POS',
    bar_mock_kegs: 'ΒΑΡΕΛΙΑ',
    bar_mock_kegs_val: '24 Βαρέλια',
    bar_mock_variance: 'ΑΠΟΚΛΙΣΗ',
    bar_mock_batch: 'ΠΑΡΤΙΔΑ #492',
    bar_mock_kegging: 'ΒΑΡΕΛΟΠΟΙΗΣΗ',
    protocol_phase1_label: 'Φάση 1',
    protocol_phase2_label: 'Φάση 2',
    protocol_phase3_label: 'Φάση 3',
    f10_title: 'Αποκλίσεις & Φθορά',
    f10_desc: 'Εντοπίστε αποκλίσεις μεταξύ θεωρητικών πωλήσεων POS και πραγματικού αποθέματος.',
    f10_ex1: 'Αναφορά θεωρητικού vs πραγματικού',
    f10_ex2: 'Δήλωση χυσίματος/φθοράς',
    f10_ex3: 'Ειδοποιήσεις κρίσιμων απωλειών',
    f11_title: 'Παραγωγή Ζυθοποιίας',
    f11_desc: 'Παρακολουθήστε τις παρτίδες μπύρας σας από ζύμωση σε βαρέλια και εμφιάλωση.',
    f11_ex1: 'Πίνακας Kanban παρτίδων',
    f11_ex2: 'Μεταφορές σταδίων',
    f11_ex3: 'Παρακολούθηση ημερών ζύμωσης',
    utility_mock_energy: 'Ηλεκτρική Ενέργεια',
    utility_mock_water: 'Νερό',
  },
  Pricing: {
    badge_free: 'Δωρεάν',
    tier_essential_name: 'Essence',
    tier_essential_badge: 'Δωρεάν',
    tier_essential_desc: 'Ξεκινήστε με τα βασικά εργαλεία.',
    tier_performance_name: 'Horizon',
    tier_performance_badge: 'Δημοφιλές',
    tier_performance_desc: 'Αυτοματοποιήστε τις λειτουργίες σας.',
    tier_enterprise_name: 'Enterprise',
    tier_enterprise_badge: 'Προσαρμοσμένο',
    tier_enterprise_desc: 'Για αλυσίδες εστιατορίων.',
    cta_trial: 'Δοκιμάστε δωρεάν',
    cta_contact: 'Επικοινωνήστε μαζί μας',
    feature_editor: 'Επεξεργαστής Μενού + QR',
    feature_i18n: 'Πολύγλωσση Ομάδα ({count} γλώσσες)',
    feature_foodcost: 'Κόστος Τροφίμων & Περιθώρια',
    feature_bcg: 'Μηχανική Μενού (BCG)',
    feature_insta: 'Δημιουργός Instagram AI',
    feature_ocr: 'Σαρωτής Αποδείξεων OCR',
    feature_deposits: 'Παρακολούθηση Εγγυήσεων',
    feature_variance: 'Αποκλίσεις & Φθορά',
    feature_production: 'Παραγωγή Ζυθοποιίας',
    feature_unlimited_financial: 'Απεριόριστες οικονομικές αναλύσεις',
    feature_unlimited_all: 'Απεριόριστη πρόσβαση σε όλα τα χαρακτηριστικά',
    feature_support: 'Υποστήριξη προτεραιότητας',
    month: '/μήνα',
    powered_by: 'Τροφοδοτείται από',
    nav_login: 'Σύνδεση',
    tier_intelligence_name: 'Intelligence',
    tier_intelligence_badge: 'Pro',
    tier_intelligence_desc: 'Πλήρης ευφυΐα δεδομένων.',
    feature_preplists: 'Έξυπνες Λίστες Προετοιμασίας AI',
    waste_calculator_title: 'Πόσο σας κοστίζει η αβεβαιότητα;',
    waste_calculator_subtitle: 'Εκτιμήστε το κόστος υπερπαραγωγής χωρίς αξιόπιστα δεδομένα.',
    section_get: 'Τι Περιλαμβάνεται',
    cta_start: 'Ξεκινήστε',
    pricing_includes: 'Περιλαμβάνει',
    pricing_popular: 'Πιο δημοφιλές',
    enterprise_custom_title: 'Προσαρμοσμένη Λύση',
    enterprise_custom_desc: 'Για αλυσίδες πολλαπλών τοποθεσιών με εξειδικευμένες ανάγκες.',
    enterprise_custom_cta: 'Επικοινωνήστε με τις Πωλήσεις',
    footer_desc: 'Αλγοριθμική ευφυΐα για γαστρονομικά εστιατόρια.',
    footer_status: 'Σύστημα Λειτουργικό',
    footer_rights: '© 2026 RiveHub. Με επιφύλαξη παντός δικαιώματος.',
    footer_privacy: 'Πολιτική Απορρήτου',
    footer_terms: 'Όροι Χρήσης',
    nano_banana_title: 'Η Ταξιαρχία',
    nano_banana_subtitle: 'Πολύγλωσση ομάδα σας',
    nb_haccp_title: 'HACCP Runner',
    nb_haccp_desc: 'Αυτοματοποιημένοι έλεγχοι συμμόρφωσης',
    nb_sonar_title: 'Sonar',
    nb_sonar_desc: 'Ελέγχοι & μήτρα δεξιοτήτων',
    nb_ocr_title: 'Ο Φακός',
    nb_ocr_desc: 'Σάρωση τιμολογίων OCR',
    nb_voice_title: 'Φωνητική Υπαγόρευση',
    nb_voice_desc: 'Σημειώσεις AI με φωνή',
    features_title: 'Χαρακτηριστικά',
    f1_title: 'Ευφυές Ημερολόγιο',
    f1_desc: 'Σημειώσεις AI, αυτόματη ταξινόμηση, επείγοντα.',
    f1_ex1: 'Αυτόματη ταξινόμηση',
    f1_ex2: 'Μετάφραση σε πραγματικό χρόνο',
    f1_ex3: 'Εξαγωγή αναφοράς',
    f2_title: 'Κόστος Τροφίμων',
    f2_desc: 'Αυτόματος υπολογισμός περιθωρίου ανά πιάτο.',
    f2_ex1: 'Κόστος ανά μερίδα',
    f2_ex2: 'Ειδοποιήσεις πληθωρισμού',
    f2_ex3: 'Κόστος εργασίας',
    f3_title: 'Πολύγλωσσο Πλήρωμα',
    f3_desc: 'Κάθε μέλος γράφει στη μητρική γλώσσα.',
    f3_ex1: 'Αυτόματη ανίχνευση γλώσσας',
    f3_ex2: 'Κάρτες συνταγών μεταφρασμένες',
    f3_ex3: 'Διαδικασίες ασφαλείας',
    f4_title: 'Σαρωτής OCR',
    f4_desc: 'Βγάλτε φωτογραφία ένα τιμολόγιο. Η AI εξάγει τα πάντα.',
    f4_ex1: 'Εξαγωγή Claude Vision',
    f4_ex2: 'Ενημέρωση τιμών',
    f4_ex3: 'Ανίχνευση μετακίνησης τιμών',
    f5_title: 'Μηχανική Μενού',
    f5_desc: 'Ταξινόμηση BCG με AI.',
    f5_ex1: 'Μήτρα BCG',
    f5_ex2: 'Συστάσεις AI',
    f5_ex3: 'Δεδομένα POS',
    f6_title: 'Δημιουργός Instagram',
    f6_desc: 'Δημοσιεύσεις AI για τα πιάτα σας.',
    f6_ex1: 'Λεζάντες AI',
    f6_ex2: 'Hashtags',
    f6_ex3: 'Βέλτιστη ώρα',
    f7_title: 'Έξυπνη Προετοιμασία',
    f7_desc: 'Λίστες AI βασισμένες σε κρατήσεις.',
    f7_ex1: 'Πρόβλεψη ανά πιάτο',
    f7_ex2: 'Κρατήσεις',
    f7_ex3: 'Ανατροφοδότηση',
    f8_title: 'Κρατήσεις',
    f8_desc: 'Ζωντανή ροή από Libro, Resy, Zenchef.',
    f8_ex1: 'Πολλαπλές πλατφόρμες',
    f8_ex2: 'Πρόβλεψη',
    f8_ex3: 'Ιστορικό',
    philosophy_approach: 'Η Προσέγγισή μας',
    f9_title: 'Εγγυήσεις',
    f9_desc: 'Παρακολούθηση βαρελιών και εγγυήσεων.',
    f9_ex1: 'Εξαγωγή OCR',
    f9_ex2: 'Κατάσταση',
    f9_ex3: 'Ανάκτηση πίστωσης',
    beta_badge: 'BETA',
  },
  Auth: {
    login_card_title: 'Καλώς ήρθατε πίσω',
    login_card_desc: 'Συνδεθείτε στο κέντρο διοίκησής σας',
    placeholder_email: 'email@example.com',
    error_auth: 'Σφάλμα ταυτοποίησης. Ελέγξτε τα στοιχεία σας.',
    btn_loading_login: 'Σύνδεση...',
    no_account: 'Δεν έχετε λογαριασμό;',
    signup_card_title: 'Δημιουργήστε το κέντρο σας',
    signup_card_desc: 'Ξεκινήστε δωρεάν σε 30 δευτερόλεπτα',
    label_name: 'Πλήρες όνομα',
    placeholder_name: 'Όνομα Επώνυμο',
    error_empty: 'Αυτό το πεδίο είναι υποχρεωτικό.',
    error_creation: 'Σφάλμα κατά τη δημιουργία λογαριασμού.',
    error_confirm: 'Οι κωδικοί δεν ταιριάζουν.',
    error_name_too_short: 'Το όνομα πρέπει να έχει τουλάχιστον 2 χαρακτήρες.',
    error_name_too_long: 'Το όνομα πρέπει να έχει λιγότερους από 50 χαρακτήρες.',
    error_name_gibberish: 'Παρακαλούμε εισάγετε ένα έγκυρο όνομα.',
    error_turnstile: 'Παρακαλούμε ολοκληρώστε την επαλήθευση ασφαλείας.',
    btn_loading_signup: 'Δημιουργία...',
    has_account: 'Έχετε ήδη λογαριασμό;',
    terms_agreement: 'Με την εγγραφή, αποδέχεστε τους',
    terms_link: 'Όρους Χρήσης',
  },
  Dashboard: {
    system_operational: 'Σύστημα Λειτουργικό',
    header_title: 'Πίνακας Ελέγχου',
    section_tasks: 'Εργασίες',
    no_tasks: 'Δεν υπάρχουν εργασίες.',
    status_completed: 'Ολοκληρώθηκε',
    status_todo: 'Προς υλοποίηση',
    tasks_to_review: 'Εργασίες προς αξιολόγηση',
    btn_review: 'Αξιολόγηση',
    btn_start: 'Έναρξη',
    section_logbook: 'Ημερολόγιο',
    welcome_back: 'Καλώς ήρθατε πίσω',
    setup_guide: 'Οδηγός Ρύθμισης',
    quick_actions: 'Γρήγορες Ενέργειες',
    stat_menu_items: 'Στοιχεία Μενού',
    stat_log_entries: 'Εγγραφές Ημερολογίου',
    stat_tier: 'Πλάνο',
    action_scan: 'Σάρωση Τιμολογίου',
    action_menu: 'Επεξεργασία Μενού',
    action_social: 'Κοινωνικά Δίκτυα',
    action_team: 'Ομάδα',
    setup_menu_title: 'Ρυθμίστε το μενού σας',
    setup_menu_desc: 'Προσθέστε πιάτα και κατηγορίες στο μενού σας.',
    setup_pos_title: 'Συνδέστε το POS σας',
    setup_pos_desc: 'Συνδέστε Toast, Square ή Lightspeed.',
    setup_team_title: 'Προσκαλέστε την ομάδα σας',
    setup_team_desc: 'Προσκαλέστε μέλη στο χώρο εργασίας σας.',
    setup_completed: 'Ολοκληρώθηκε',
    stat_intelligence: 'Ευφυΐα',
    weekly_schedule: 'Εβδομαδιαίο Πρόγραμμα',
    all_months: 'Όλοι οι μήνες',
    add_availability: 'Προσθήκη διαθεσιμότητας',
    task_prep_lists: 'Λίστες Προετοιμασίας',
    health_score: 'Βαθμολογία Υγείας',
    not_calculated: 'Δεν υπολογίστηκε',
    view_details: 'Δείτε λεπτομέρειες',
    live_utility_costs: 'Ζωντανά Κόστη Υπηρεσιών',
    monthly_energy: 'Μηνιαία Ενέργεια',
    monthly_water: 'Μηνιαίο Νερό',
    last_30_days: 'Τελευταίες 30 ημέρες',
    schedule_day_wed: 'Τετ',
    schedule_day_tue: 'Τρι',
    schedule_day_thu: 'Πεμ',
    schedule_day_fri: 'Παρ',
    schedule_day_sat: 'Σαβ',
    schedule_role_server: 'Σερβιτόρος',
    schedule_role_bartender: 'Barman',
    task_smoothie: 'Smoothie',
    task_restock: 'Ανανέωση αποθέματος',
    task_temps: 'Θερμοκρασίες',
    task_availability: 'Διαθεσιμότητα',
    chart_monthly_label: 'Μηνιαίο',
    chart_current_label: 'Τρέχον',
    chart_water_label: 'Νερό',
    month_jul: 'Ιούλ',
    month_aug: 'Αύγ',
    month_sep: 'Σεπ',
    month_oct: 'Οκτ',
    month_nov: 'Νοέ',
    month_dec: 'Δεκ',
    month_jan: 'Ιαν',
  },
  Instagram: {
    desc: 'Δημιουργήστε δημοσιεύσεις AI για τα πιάτα σας',
    btn_loading: 'Δημιουργία...',
    btn_retry: 'Δοκιμάστε ξανά',
    btn_copied: 'Αντιγράφηκε!',
    quota_reached: 'Όριο quota επιτεύχθηκε',
    quota_desc: 'Έχετε χρησιμοποιήσει όλα τα δωρεάν credits δημιουργίας Instagram.',
    eng_version: 'Αγγλική έκδοση',
    best_time: 'Βέλτιστη ώρα δημοσίευσης',
    error_conn: 'Σφάλμα σύνδεσης',
  },
  Logbook: {
    placeholder: 'Γράψτε μια σημείωση σε οποιαδήποτε γλώσσα...',
    btn_loading: 'Φόρτωση...',
    scan_title: 'Σάρωση Τιμολογίου',
    btn_scan: 'Σάρωση',
    scan_loading: 'Σάρωση...',
    quota_reached: 'Όριο quota επιτεύχθηκε',
    quota_desc: 'Έχετε χρησιμοποιήσει όλες τις δωρεάν σημειώσεις AI.',
    scan_quota_desc: 'Έχετε χρησιμοποιήσει όλες τις δωρεάν σαρώσεις.',
    last_entries: 'Τελευταίες εγγραφές',
    view_lang: 'Εμφάνιση στα',
    ai_summary: 'Σύνοψη AI',
    urgent: 'Επείγον',
    extracted_data: 'Εξαχθέντα δεδομένα',
    supplier: 'Προμηθευτής',
    amount: 'Ποσό',
    items: 'Στοιχεία',
    empty_state: 'Δεν υπάρχουν σημειώσεις ακόμα. Γράψτε τη πρώτη σας!',
    image_ready: 'Εικόνα έτοιμη',
    notes_used: 'Σημειώσεις χρησιμοποιημένες',
    scans_used: 'Σαρώσεις χρησιμοποιημένες',
    translated_badge: 'Μεταφρασμένο',
    translation_quota_reached: 'Όριο μεταφράσεων επιτεύχθηκε',
    translating: 'Μετάφραση...',
    translate_to: 'Μετάφραση σε',
    btn_delete_title: 'Διαγραφή',
    label_date: 'Ημερομηνία',
  },
  MenuEditor: {
    desc: 'Δημιουργία, επεξεργασία και δημοσίευση του μενού σας',
    btn_view_qr: 'Προβολή QR',
    btn_show_qr: 'Εμφάνιση QR',
    btn_hide_qr: 'Απόκρυψη QR',
    qr_scan_prompt: 'Σαρώστε για να δείτε το μενού',
    status_unavailable: 'Μη διαθέσιμο',
    btn_edit: 'Επεξεργασία',
    btn_hide: 'Απόκρυψη',
    btn_show: 'Εμφάνιση',
    btn_delete: 'Διαγραφή',
    no_items: 'Δεν υπάρχουν στοιχεία στο μενού.',
    form_new: 'Νέο πιάτο',
    form_edit: 'Επεξεργασία πιάτου',
    label_desc: 'Περιγραφή',
    placeholder_allergens: 'π.χ.: γλουτένη, ξηροί καρποί',
    btn_cancel: 'Ακύρωση',
  },
  MenuEngineering: {
    desc_full: 'Ταξινόμηση BCG και βελτιστοποίηση μενού βασισμένη σε AI.',
    desc_short: 'Ανάλυση απόδοσης μενού',
    median_info: 'Ο διάμεσος χρησιμοποιείται ως σημείο αναφοράς',
    btn_generate: 'Δημιουργία ανάλυσης',
    btn_generating: 'Δημιουργία...',
    analyzing: 'Ανάλυση...',
    quota_reached: 'Όριο quota επιτεύχθηκε',
    quota_desc: 'Έχετε χρησιμοποιήσει όλες τις δωρεάν αναλύσεις μενού.',
    quota_usage: 'Χρήση quota',
    table_title: 'Αποτελέσματα Ανάλυσης',
    profit_label: 'Κέρδος',
    orders_label: 'Παραγγελίες',
    margin_label: 'Περιθώριο',
    axis_pop: 'Δημοφιλές',
    axis_impop: 'Μη δημοφιλές',
    cat_phare: 'Φάρος',
    cat_phare_desc: 'Υψηλή δημοτικότητα & υψηλό περιθώριο',
    cat_ancre: 'Άγκυρα',
    cat_ancre_desc: 'Υψηλή δημοτικότητα & χαμηλό περιθώριο',
    cat_derive: 'Παρέκκλιση',
    cat_derive_desc: 'Χαμηλή δημοτικότητα & υψηλό περιθώριο',
    cat_ecueil: 'Ύφαλος',
    cat_ecueil_desc: 'Χαμηλή δημοτικότητα & χαμηλό περιθώριο',
  },
  Settings: {
    module_social_hub_label: 'Κέντρο Κοινωνικών Δικτύων',
    module_social_hub_desc: 'Δημοσιεύσεις AI, σύνδεση Meta & TikTok',
    module_logbook_quote: 'Αρχεία καταγραφής AI',
  },
  LandingMockups: {
    invoice_alert_el: '+12% σε σχέση με τον προηγούμενο μήνα',
    bar_variance_val: 'Ειδοποίηση Ενεργή',
    bar_batch_status: 'Ζύμωση',
    mock_beer1_style: 'IPA',
  },
  SettingsIntegrations: {
    error_save: 'Σφάλμα κατά την αποθήκευση.',
    placeholder_api_key: 'Εισάγετε κλειδί API...',
    label_api_key_help: 'Βρείτε αυτό στις ρυθμίσεις προγραμματιστή.',
    success_test: 'Η σύνδεση δοκιμάστηκε επιτυχώς.',
    btn_test: 'Δοκιμή σύνδεσης',
    btn_remove: 'Αφαίρεση σύνδεσης',
  },
  SettingsReservations: {
    error_save: 'Σφάλμα κατά την αποθήκευση.',
    btn_disconnect: 'Αποσύνδεση',
    confirm_disconnect: 'Αποσύνδεση αυτής της πλατφόρμας;',
    error_invalid_key: 'Μη έγκυρο κλειδί API.',
  },
  Barometre: {
    no_data: 'Δεν υπάρχουν διαθέσιμα δεδομένα',
    error_loading: 'Σφάλμα φόρτωσης δεδομένων βαρομέτρου',
  },
  NauticalCommandCenter: {
    feed_empty: 'Δεν υπάρχουν γεγονότα ακόμα.',
  },
};

// Apply patches
for (const [section, keys] of Object.entries(patch)) {
  if (!el[section]) el[section] = {};
  for (const [key, value] of Object.entries(keys)) {
    el[section][key] = value;
  }
}

fs.writeFileSync(path.join(__dirname, '../messages/el.json'), JSON.stringify(el, null, 2) + '\n', 'utf8');
console.log('Patch applied successfully.');
